# Generated by Django 5.0.7 on 2025-08-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='can_edit',
            field=models.BooleanField(default=True, verbose_name='Pode Editar'),
        ),
    ]