# Generated by Django 5.0.7 on 2025-08-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramais', '0002_add_can_edit_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='teams',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Teams'),
        ),
    ]
